### ISSUE TITLE
Disarm can be used to farm Witches for potions.

### ISSUE THREAD

**Issue by Sourpowerpete** [TeamWizardry/Wizardry#18]
https://gfycat.com/RightUnsungGuineapig

**Comment by BionicFelps** [comment]
Seems to work, what's the issue? :P

**Comment by murapix** [comment]
The issue is that it's free items that could potentially be very useful, especially once we implement auto-casting. There are other cases where this is more problematic, such as casting it on Zombie Pigmen to get free gold swords, which you can then melt down for a lot more gold than normal farming methods. This spell in particular is focused more around PvP, making it a farming method rather than a defensive combat measure is not where we want it to go, and just feels exploit-y. I don't think it would hurt to leave it in as a config option though, for those who want it to be used as such.

**Comment by LordSaad44** [comment]
It literally makes no sense and is just stupid.... I ain't configing that.

**Comment by murapix** [comment]
Fixed in fcd7925537424efeb7ec83c577b89e338caa18e9
