### ISSUE TITLE
No flying Items at spell creation forge

### ISSUE THREAD

**Issue by PresquePlayed** [TeamWizardry/Wizardry#230]
If you right click items on the spell forge they dont show up as they did in previouse versions

**Comment by Demoniaque** [comment]
Need more information

**Comment by PresquePlayed** [comment]
yeah and spell creation works perfectly but I can't see the items..

**Comment by Demoniaque** [comment]
Are you on a server

**Comment by PresquePlayed** [comment]
no but I tested it again this time I uninstalled everything exept optifine now I could see the items start flying around but after a few seconds they disappeared again

**Comment by Xechon** [comment]
To add to this, I am experiencing this in a singleplayer world in dev environment. Items only render floating around table on world rejoin, although they dissapear when taken out properly. The crafting animation does play properly if the items are rendering, but only the particles from the pearl holders render otherwise. I don't have a firm grasp of all this render stuff yet, so I hope this info helps.

**Comment by SwissCheese5** [comment]
Cannot reproduce. Comment here if it happens again.
