### ISSUE TITLE
Getting stuck in Mana Pools

### ISSUE THREAD

**Issue by Ariannae** [TeamWizardry/Wizardry#231]
I'm fairly certain this wasn't an issue in previous versions, but using 0.9.9 and jumping into a mana pool causes my character to get stuck. The Ascension (de?)buff is applied to my character but does not cause them to float upwards. It does, however, lock my character out from jumping.

This means that if I do not have access to flying or am not in creative mode, my character gets stuck in the mana pool, unable to escape because they can not get above the block level that the pool is on.

**Comment by sProgg** [comment]
Also getting this problem.

**Comment by murapix** [comment]
Not actually a new issue at all, it's been occasionally happening ever since we first made mana pools. There's *some* skill involved in making sure it doesn't happen, but that's not always doable. I'll see if I can do anything about it, but there might not be much we can do while still letting you do things like grab items at the bottoms of pools.

**Comment by Demoniaque** [comment]
Perhaps we can listen to the jump event and push the player upwards by force?

**Comment by AstaricPlayz** [comment]
There is a way to get out... You can use a water bucket to suck the mana from underneath you, but I just wish that you can get out as if it was normal water.....

**Comment by Demoniaque** [comment]
Applied a small vertical force while in the pool. Will be in the next version
