### ISSUE TITLE
0.10.0 and Latest Library - Random Crash

### ISSUE THREAD

**Issue by HalestormXV** [TeamWizardry/Wizardry#274]
Random Crashes on 0.10.0 and latest Library. I can't seem to track it. Perhaps it has to do with Particle Effects or Shift clicking?

Crash Report
https://hastebin.com/iheyajukew.rb

This reproduces randomly. It has reproduced when I was around mobs with some particles and when I have tried shift clicking an item stack into a container (modded or vanilla chest even). I don't have much more to go on because it is seemingly random and I have no way to accurately reproduce it.

**Comment by Bluexin** [comment]
https://github.com/TeamWizardry/Wizardry/blob/989be412eb1401492bb0c783058cdba07517df95/src/main/java/com/teamwizardry/wizardry/common/tile/TileLight.java#L64

You are spawning particles in the TE's `update` method, which can happen concurrently with client ticking, which is used to update particles.

My recommendations:
 * try to move to the new particle system if you can
 * use a custom renderer instead of this TE ticking hax (which is not at all meant for that kind of thing)

**Comment by SwissCheese5** [comment]
Ah, my bad. I'll add a world.isremote check and that should be that.

**Comment by Bluexin** [comment]
You missed the point of my whole comment, see discord

**Comment by Bluexin** [comment]
After further consideration, it might fix it. I still recommend removing the whole ClientRunnable part as that will just create unnecessary inner classes instances.
