### ISSUE TITLE
Backup Component causes a crash upon activation

### ISSUE THREAD

**Issue by Sourpowerpete** [TeamWizardry/Wizardry#28]
https://gfycat.com/EssentialVerifiableIrishterrier
https://pastebin.com/uAQ9Xvnb

**Comment by murapix** [comment]
Should be fixed now, the summoned zombies were asking for an entity's data at a specific memory location, dictated by the EntityDataManager - but if the entity didn't have that data, the data manager would just return whatever object *was* there. Queue crashing because the zombie was asking for a UUID, the manager was giving it an integer.

Also, the summoned zombies were dropping normal zombie loot and xp, so I put a stop to that too.
