### ISSUE TITLE
crash with xaeros map

### ISSUE THREAD

**Issue by pibblepower** [TeamWizardry/Wizardry#343]
to reproduce the issue, spawn a fairy with xaeros minimal and xaeoros world map installed. as soon as the fairy has a chance to register on the map, the game crashes. 
[crash-2021-08-24_16.34.52-client.txt](https://github.com/TeamWizardry/Wizardry/files/7042175/crash-2021-08-24_16.34.52-client.txt)

**Comment by murapix** [comment]
Ok, I see what's going on here - we've set the Fairy to have a null texture, due to it only rendering via particles rather than a standard mob entity, and Xaero's just doesn't think of that case (decent assumption to make, but ends up being wrong here). I *hope* they'll be willing to fix it, it'll be annoying for us to get things set back up on our side, but if not then I'll push through that.

**Comment by SwissCheese5** [comment]
I think we already have a transparent texture we can use

**Comment by thexaero** [comment]
@murapix This is actually no longer an issue in the latest version of my minimap. They are using an old one.

**Comment by SwissCheese5** [comment]
@thexaero Thank you so much.
