### ISSUE TITLE
mana battery crash with fluidapi

### ISSUE THREAD

**Issue by ralseilii** [TeamWizardry/Wizardry#353]
when you have fluidapi mod(Fluidlogged-API-v2.2.7, from https://modrinth.com/mod/fluidlogged-api), right click mana battery will cause crash

**Comment by Hadaward** [comment]
Sorry but this problem seems to come from Fluid Logged API itself, it is not a problem in Wizardry, but rather in the way Fluid Logged is handling the rendering of the Wizardry hologram block.

![image](https://github.com/TeamWizardry/Wizardry/assets/24706265/41f5fb3a-0f28-47a7-afdf-a26771cbe44e)

[StructureManager.java#L144](https://github.com/TeamWizardry/Wizardry/blob/master/src/main/java/com/teamwizardry/wizardry/api/structure/StructureManager.java#L144)

I made a new issue for you there:
[Wizardry Hologram crashing the world in presence of Fluid Logged](https://github.com/jbredwards/Fluidlogged-API/issues/197)

**Comment by PhotonChaos** [comment]
Issue is fixed in dev for Fluid Logged API, closing here.
