### ISSUE TITLE
Question marks sprinkled throughout Codex

### ISSUE THREAD

**Issue by Jacobeta** [TeamWizardry/Wizardry#36]
Reading through the Codex, you can notice strange characters ( [?][?][?] ) where apostrophes and other letters should be.

Screenshot:
![2017-09-16_15 09 56](https://user-images.githubusercontent.com/8630389/30515280-c6cdfec8-9af2-11e7-840b-f89c8cd742e1.png)

**Comment by DelfCo** [comment]
Looks like all the em dashes and 'smart' single quotes are causing this. Is the fix to change the text, or do you consider it a bug in the code that displays them using the wrong code page?

**Comment by LordSaad44** [comment]
I got no clue. It's scrambling apostraphes but not in my dev environment. Weird...

**Comment by DelfCo** [comment]
I've attached a copy of the nacre-pearls.json file, with what I believe are the problem characters corrected. If you take this copy of the file instead of the one currently checked in, and that one page doesn't show the ??? anymore, I can do a pull request that fixes those characters on all the pages under documentation/en_us. (I'm not currently set up to build the project and test it myself, but if it's just the text changes, I can clone the repo and do those changes. I'll just need a buddy build from someone who can make sure I didn't mess anything else up in the process.)

I had to add .txt to the filename to get GitHub to let me attach it. you'll need to change the name back when you test it.
[nacre_pearls.json.txt](https://github.com/TeamWizardry/Wizardry/files/1315789/nacre_pearls.json.txt)

**Comment by Jacobeta** [comment]
The json file, at least for me, looks good. The question blocks are not there anymore.

**Comment by LordSaad44** [comment]
@DelfCo What exactly did you change in the json? I can't spot a difference.

**Comment by DelfCo** [comment]
I changed two things:
* changed ’ (HTML \&apos;) to ' (ASCII code 39 decimal). The first is an apostrophe, which looks like an inverted comma, so it tilts down and to the left; the replacement is the standard single quote character, which is vertical.
* changed – (HTML \&mdash;) to -- (Two consecutive ASCII code 45 decimal). The first is a long, or 'em' dash, a horizontal line the same width as the font height; the replacement is two shorter hyphens, which is a conventional way to indicate a dash that dates back to manual typewriting. (Dashes and hyphens have different functions in English, so you don't just want to use a single hyphen.)

What's going on is that the parser and the text rendering code are not agreeing about which character encoding scheme is being used. So the 'fancy' apostrophe and em dash in the JSON are not displayable using whichever code page the display code is using. The ??? is what the display code displays when it gets a character it doesn't understand. Almost all encoding schemes are designed to pass ASCII characters through unchanged, which is why my changes work -- I've reduced things to the lowest common denominator, seven-bit ASCII. There should be a way to deal with this in the code that reads the JSON and/or the code that displays the text from the JSON, but I'm a C/C++/C# guy, not a Java guy, so I have no idea how to do that in a Minecraft mod.

The reason that some of us don't see differences might be down to different OSs or locale settings, so that the default encodings happen to match for some, but not for everyone.

**Comment by Demoniaque** [comment]
@DelfCo I just developed a small tool that does exactly what you said and it works perfectly. :) https://i.imgur.com/OHPAAHu.png

The tool lets you choose multiple files and it will instantly convert them all. Thank you for helping me out. If there are any other symbols I should look out for, please tell me.

This is the core of the code:

`		try {
				List<String> fileContent = new ArrayList<>(Files.readAllLines(Paths.get(file.getPath()), StandardCharsets.UTF_8));

				for (int i = 0; i < fileContent.size(); i++) {
					fileContent.set(i, fileContent.get(i).replace("’", "'").replace("–", "--"));
				}

				Files.write(Paths.get(file.getPath()), fileContent, StandardCharsets.UTF_8);
			} catch (IOException e) {
				e.printStackTrace();
			}`

https://i.imgur.com/Qia24Ft.png fixed all the files. Will be in the next update.

https://github.com/Demoniaque/html-to-ascii-converter
