### ISSUE TITLE
Crashes on startup if dependencies are missing, rather than displaying a message

### ISSUE THREAD

**Issue by Kevun1** [TeamWizardry/Wizardry#62]
On load, Wizardry simply causes a crash if LibrarianLib is missing. No crash log is created, so players may have a hard time finding the cause of the crash. Typically, if mods are missing any dependencies, they don't crash the game on load but instead stop the game from loading and display a message to the player telling them what dependencies they are missing.

**Comment by murapix** [comment]
Yeah, I just recently experienced this myself, and am currently thinking it's because of a Forge update that's more recent than what we're building on. Not completely sure what the problem is though, just that it worked fine on previous versions, and at some point between then and now, stopped working.

**Comment by Demoniaque** [comment]
@murapix any updates here?

**Comment by murapix** [comment]
Turns out the `useMetadata` flag in the @Mod annotation makes it just ignore the data in the annotation, and use the mcmod.info file instead, which in this case, did not have LibLib as a required dependency. I've removed that flag for now, if that turns out to cause other issues, we can reenable it and add LibLib as a dependency in the mcmod.info file instead.
