### ISSUE TITLE
Mining Redstone Ore Crashes The Server

### ISSUE THREAD

**Issue by Ragnarok96** [TeamWizardry/Wizardry#96]
Everytime redstone ore was mined, the console would get spammed with stuff, players timed out and eventually the server would crash.

Deleting the wizardymod jar resolved the issue and the ore could be mined successfully again.

Please view the crash report below:

https://pastebin.com/X1YSsvuG

**Comment by murapix** [comment]
Yeah, this is my bad, I forgot to see how FluxNetworks and Wizardry would interact, since we're using the same crafting methods for some of our recipes. Don't report it on his end, this is something I need to fix on my end.

**Comment by Ragnarok96** [comment]
Ah so it's only a conflict between the two? some mods add extra drops so I didn't know if they would interfere however I saw a mention of wizardry so tried that being the newest not yet finished mod as a first go to but that would also make sense as to why flux and wizardry were both mentioned alongside forge.

**Comment by murapix** [comment]
We're both replacing normal item entities with our own custom ones, since normal item entities just ignore all attempts to keep them from instantly disappearing upon touching fire, but there's no way to have both at once - a fruit can be an apple or an orange, but it can't be both - so I'm making Flux Networks take priority here, and adding an alternate recipe for our Devil Dust, instead of having both mods just replacing the item entity with their own version endlessly, as is happening right now.

**Comment by murapix** [comment]
Should be fixed with the latest version
